### PR TITLE
Close mobile sidebar by click outside it + navbar

### LINKED ISSUE #130: Hamburger menu not working on mobile
Reported by ahmetlii

Steps to reproduce:
1. Open the Wiki on a mobile browser (I used Firefox Android)
2. Click the hamburger menu at the top left

Expected behavior: sidebar opens
Actual behavior: sidebar does not open (nothing happens)

### PR DESCRIPTION
**Pull request by Kenny2github**
That is, after opening the sidebar on mobile, you can now tap anywhere outside both the sidebar and the navbar to close the sidebar.

I just thought this would be a good idea. Check it out on my test wiki: https://test-wiki.abyx.dev

Demo:

This PR in action

This also fixes #130

### CODE REVIEW

**Review by jacob-g — COMMENTED** [review]
This passes functional testing and I can't find any regressions.

File: ScratchWikiSkinTemplate.php [hunk 1]
```diff
@@ -364,15 +364,31 @@ function mod(el) {
...
+		left.style.left = '0';
+		notNav.addEventListener('click', toggleSidebar);
 	} else {
-		document.querySelector('#view .inner .left').style.left = null;
+		// ignore clicks in the sidebar itself
+		if (left.contains(e.target)) return;
+		// hide sidebar and disable non-nav close listener
+		e.preventDefault();
+		left.style.left = null;
+		notNav.removeEventListener('click', toggleSidebar);
```
Comment (jacob-g) [inline ScratchWikiSkinTemplate.php:386]: I looked in the inspector and the event is properly added and removed.

**Review by jacob-g — APPROVED** [review]
Looks good. Passes code review and functional testing.
